import { tcpdBriefing, tcpdPolicy } from "./public-records";

export const risks = [
  { id: "01", title: "Your routines become records.", short: "A plate scan can say more than you think.", detail: "TCPD’s policy describes records containing vehicle images, plate numbers, timestamps, and locations. Repeated sightings can reveal patterns around work, worship, or medical visits. A record of a vehicle does not establish who was driving.", question: "Who can search for our vehicles, and for what reasons?", source: `${tcpdPolicy.href}#page=2` },
  { id: "02", title: "Local data can travel.", short: "A local camera can feed a wider network.", detail: "TCPD’s policy permits sharing with authorized law enforcement or public safety agencies for legitimate purposes. That rule does not identify the sharing partners currently enabled in the system.", question: "Which agencies can access Tell City’s records?", source: `${tcpdPolicy.href}#page=9` },
  { id: "03", title: "A match isn’t proof.", short: "A vehicle sighting doesn’t identify its driver.", detail: "TCPD’s policy treats alerts as investigative leads and requires independent verification before enforcement. It prohibits a traffic stop based solely on an unverified ALPR alert. Residents deserve to know how that safeguard works in practice.", question: "How does TCPD verify alerts before taking action?", source: `${tcpdPolicy.href}#page=4` },
  { id: "04", title: "The rules matter.", short: "Collection is only the beginning.", detail: "TCPD’s policy ties routine retention to its approved Flock configuration without specifying a fixed number of days. It requires an audit at least annually and allows evidence to be preserved for investigations or legal holds.", question: "What are the actual retention settings and audit findings?", source: `${tcpdPolicy.href}#page=8` },
];

type Faq = { q: string; a: string; source?: { label: string; href: string } };

export const faqs: Faq[] = [
  { q: "What are Flock cameras and ALPRs?", a: "ALPR stands for automated license plate reader. These cameras photograph plates and turn sightings into searchable records. Flock Safety is one vendor. A record can include a plate number, vehicle characteristics, time, and location. This site focuses on that technology, rather than every type of security camera." },
  { q: "Aren’t the cameras meant to help solve crimes?", a: "Yes. TCPD’s council briefing describes investigations and missing-person cases in which the department says ALPR helped. Those benefits deserve consideration alongside the privacy cost of routinely recording vehicles whose drivers are not suspected of a crime.", source: tcpdBriefing },
  { q: "If I’m doing nothing wrong, why should I worry?", a: "You don’t have to be doing anything wrong to have something worth keeping private. A medical appointment, a religious service, or a visit to a friend can be nobody else’s business. The concern is not just what you are doing today; it is who can search your movements, what they might infer, and how that power could be misused. Privacy should not depend on proving you have an acceptable reason to want it. Supporting public safety does not require accepting routine surveillance of everyone." },
  { q: "Is the ankle-monitor comparison fair?", a: "It is a comparison about the principle, not an assertion that the technologies are identical. ALPRs record vehicle sightings at camera locations; they do not continuously track every resident or establish who is driving. Repeated sightings can nevertheless create a searchable picture of a vehicle’s movements. The ankle-monitor thought experiment asks where we draw the line: would a possible benefit to an investigation justify routinely recording the movements of people who are not suspected of a crime? Our answer is no." },
  { q: "What do we know about cameras in Tell City?", a: "TCPD released records with its October 2, 2026 response: an ALPR policy and acknowledgment form, the original Flock agreement, invoices, and a council briefing. The September 2026 briefing reports six cameras, a $15,000 annual cost, and a current contract expiring in 2028. Those are the department’s reported figures; the original agreement is a historical document.", source: tcpdBriefing },
  { q: "Does the TCPD response answer every records request?", a: "The October 2 response addresses the records TCPD identified and supplied. It says investigation, search, audit, and system-security records require review before release, and invites the requester to identify categories not addressed. The release does not establish that every requested category has been supplied." },
  { q: "Is this an official city website?", a: "No. DeFlock Tell City is an independent petition and educational website created by an anonymous private citizen. It is not affiliated with the City of Tell City, its police department, Flock Safety, or the Electronic Frontier Foundation. Signing records your support here; it does not automatically submit a document to the city." },
  { q: "What happens when I sign?", a: "Your signature is saved and added to the public total. Your name and ZIP code are stored privately for the petition and may be included in a future submission to city officials. Your email is converted into a protected fingerprint to prevent duplicates; the original email is not stored. Names are not displayed publicly. The count measures submissions, not independently verified identities." },
];
