export const sources = [
  { name: "How license plate readers work", publisher: "Electronic Frontier Foundation", type: "EXPLAINER", url: "https://sls.eff.org/technologies/automated-license-plate-readers-alprs?language=en" },
  { name: "Tell City’s introduction of Flock cameras", publisher: "14 News · August 7, 2021", type: "LOCAL REPORTING", url: "https://www.14news.com/2021/08/07/tell-city-police-adopts-new-camera-surveillance-system/" },
  { name: "Flock’s data and privacy policies", publisher: "Flock Safety · Vendor perspective", type: "COMPANY POLICY", url: "https://www.flocksafety.com/trust/data-privacy" },
  { name: "How Flock handles data deletion", publisher: "Flock Safety · Vendor perspective", type: "DATA RETENTION", url: "https://www.flocksafety.com/blog/how-does-flock-handle-license-plate-data-deletion" },
  { name: "ALPR searches without a warrant requirement", publisher: "Electronic Frontier Foundation · May 26, 2026", type: "INVESTIGATION", url: "https://www.eff.org/deeplinks/2026/05/more-license-plate-reader-mission-creep-school-residency-verification-background" },
];

export const risks = [
  { id: "01", title: "Your routines become records.", short: "A plate scan can say more than you think.", icon: "route", detail: "A plate, timestamp, and camera location create a record of where a vehicle was seen. Repeated sightings can reveal patterns around work, worship, or medical visits—even when a driver is not suspected of a crime.", question: "Who can search for our vehicles, and for what reasons?" },
  { id: "02", title: "Local data can travel.", short: "A local camera can feed a wider network.", icon: "network", detail: "Sharing can put vehicle sightings within reach of other agencies. Flock says customers control those sharing choices. Residents need to know which relationships are enabled, and how access is reviewed.", question: "Which agencies can access Tell City’s records?" },
  { id: "03", title: "A match isn’t proof.", short: "A vehicle sighting doesn’t identify its driver.", icon: "scan", detail: "A plate read can be mistaken, and the person driving may not be the vehicle’s owner. Flock says its ALPR product does not identify who is inside a vehicle. A search result needs independent verification.", question: "What checks happen before an alert leads to a stop?" },
  { id: "04", title: "The rules matter.", short: "Collection is only the beginning.", icon: "shield", detail: "Retention, exports, and access policies shape the impact of a camera network. Flock’s published defaults have changed; the actual retention period depends on the agency’s settings and applicable requirements. Preserved evidence may be treated differently.", question: "What is kept, for how long, and who audits its use?" },
];

export const faqs = [
  { q: "What are Flock cameras and ALPRs?", a: "ALPR stands for automated license plate reader. These cameras photograph plates and turn sightings into searchable records. Flock Safety is one vendor. A record can include a plate number, vehicle characteristics, time, and location. This site focuses on that technology, rather than every type of security camera." },
  { q: "Aren’t the cameras meant to help solve crimes?", a: "Yes. Police use ALPRs to look for stolen vehicles and investigate crimes. Tell City police described those purposes in the 2021 reporting linked below. But usefulness alone does not settle whether surveillance is acceptable. Knowing where everyone has been might help solve some crimes; that would not justify putting an ankle monitor on every resident. We should ask both whether a tool helps and whether its intrusion on ordinary people’s lives is justified." },
  { q: "If I’m doing nothing wrong, why should I worry?", a: "You don’t have to be doing anything wrong to have something worth keeping private. A medical appointment, a religious service, or a visit to a friend can be nobody else’s business. The concern is not just what you are doing today; it is who can search your movements, what they might infer, and how that power could be misused. Privacy should not depend on proving you have an acceptable reason to want it. Supporting public safety does not require accepting routine surveillance of everyone." },
  { q: "Is the ankle-monitor comparison fair?", a: "It is a comparison about the principle, not an assertion that the technologies are identical. ALPRs record vehicle sightings at camera locations; they do not continuously track every resident or establish who is driving. Repeated sightings can nevertheless create a searchable picture of a vehicle’s movements. The ankle-monitor thought experiment asks where we draw the line: would a possible benefit to an investigation justify routinely recording the movements of people who are not suspected of a crime? Our answer is no." },
  { q: "What do we know about cameras in Tell City?", a: "14 News reported Tell City’s introduction of Flock equipment in August 2021. That reporting establishes a local history, not today’s camera count or policies. Current locations, contracts, costs, sharing settings, and retention rules should be confirmed through up-to-date city records." },
  { q: "Is this an official city website?", a: "No. DeFlock Tell City is an independent petition and educational website created by an anonymous private citizen. It is not affiliated with the City of Tell City, its police department, Flock Safety, or the Electronic Frontier Foundation. Signing records your support here; it does not automatically submit a document to the city." },
  { q: "What happens when I sign?", a: "Your signature is saved and added to the public total. Your name and ZIP code are stored privately for the petition and may be included in a future submission to city officials. Your email is converted into a protected fingerprint to prevent duplicates; the original email is not stored. Names are not displayed publicly. The count measures submissions, not independently verified identities." },
];
